{{- range $key, $val := $.Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    name: ''
    namespace: {{ $key }}
    server: 'https://kubernetes.default.svc'
  source:
{{- if $val.helm }}
    helm:
      valueFiles:
{{- range $val.helm.valueFiles }}
        - {{ . }}
{{- end }}
{{- end }}
    path: '{{ $val.path }}'
    repoURL: '{{ $.Values.helmRepoUrl }}'
    targetRevision: '{{ $val.branch }}'
  project: {{ $.Values.projectName }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  
{{- end }}
{{- end }}