##
# Jump App ArgoCD Chart values
##

# Project specifications
projectName: jump-app

# ArgoCD Operator deployment
argocd:
  enabled: true
  controller: argocd-operator
  namespace: openshift-gitops

# Helm Repo GIT
helmRepoUrl: https://github.com/acidonper/jump-app-gitops.git

# ArgoCD apps definition
apps: {}

# Namespaces handled by Helm
managed_namespaces: []

